### ISSUE TITLE
class_rw_t 已经发生改变了

### ISSUE THREAD

**Issue by IanIsMyUsername** [colourful987/bytedance-alibaba-interview#4]
现在objc4_781 已经隐藏了方法列表、属性列表等这些的，封装到了 class_rw_ext_t结构，大佬有空更新一下，文章内容非常好，还在慢慢学习，受益很多，还想问下大佬有swift中关于runtime的一些思考或学习思路么

**Comment by colourful987** [comment]
最近事情有点多，之后我抽空 Update 下，感谢你的反馈哈，一起交流，可以加我微信 pmst_ftd，备注下 github 。
